### ISSUE TITLE
package.json on windows

### ISSUE THREAD

**Issue by lianyi** [aendrew/learning-d3#2]
Hi, Aendrew

I was following your book(2nd Edition) to this repo and it seems package.json won't work on windows. 

One issue is the installation:

"canvas" won't install

```
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
```

Another issue is that the following may not work on windows. 

```
"scripts": {
    "test": "mocha spec/index.js",
    "lint": "./node_modules/eslint/bin/eslint.js src/*.js",
    "start": "./node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --content-base src/"
  },
```

Maybe one way is to install the tools first

```
npm install -g mocha eslint webpack webpack-dev-server
```

then

```
"scripts": {
    "test": "mocha spec/index.js",
    "lint": "eslint src/*.js",
    "start": "webpack-dev-server --inline --content-base src/"
  },
```

**Comment by aendra-rininsland** [comment]
Hi @lianyi!

Sorry to hear you're having issues on Windows! Admittedly that's not a platform I've been able to test very extensively on.

I have some ideas about how to solve the issues you mention; please give me until this evening, then do `git pull` once I've closed this. Thanks!

**Comment by aendra-rininsland** [comment]
@lianyi Hi again! Mind pulling whichever branch you're working on and then running `npm install`? This should fix the first issue.

Also, please try `npm start` to see whether webpack-dev-server is working; it should given how I've pathed it in the repo, but again, I haven't tested super extensively on Windows.

Thanks again!

**Comment by lianyi** [comment]
Thanks @aendrew !  `npm install` working smoothly now! 

I just tested `npm start`, and a new ticket #3 was added.
